### ISSUE TITLE
error reported when import a module, but actually it works

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/vimcmdline#83]
if I use space to excute a line like "import bla", then there will be long stacktraces like below, although in fact the import actually works. 

this is not an urgent issue since it indeed sucessfully completed the import and everything else works just seemingly something is wrong: 

```
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from main import embed_cluster
Exception in default exception handler
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in _run_task
    t()
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/context.py", line 115, in new_func
    return func(*a, **kw)
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 716, in cpr_not_supported_callback
    run_in_terminal(in_terminal)
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/run_in_terminal.py", line 41, in run_in_terminal
    return run_coroutine_in_terminal(async_func, render_cli_done=render_cli_done)
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/run_in_terminal.py", line 62, in run_coroutine_in_terminal
    assert app._is_running
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/base.py", line 129, in call_exception_handler
    self._exception_handler(context)
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 692, in handle_exception
    run_coroutine_in_terminal(print_exception)
  File "/home/user/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/run_in_terminal.py", line 62, in run_coroutine_in_terminal
    assert app._is_running
AssertionError
from main import embed_cluster

In [2]: from main import embed_cluster

In [3]:
```

**Comment by smilesun** [comment]
something similar: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/976
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/auto_suggest.py#L49

**Comment by jalvesaq** [comment]
I can't replicate the issue with a code such as (or I didn't understand what is the issue at all):

```python
from sys import is_finalizing
print(is_finalizing())
```

**Comment by jalvesaq** [comment]
I have seen something similar when using virtual environments. You have to set the value of `cmdline_app` according to the environment that you are going to use. Example for `init.lua`:

```lua
vim.g.cmdline_app = {
    python = '~/.py3env/bin/python3'
}
```

And the same example for `init.vim`:

```vim
let cmdline_app = {'python': '~/.py3env/bin/python3'}
```

**Comment by jalvesaq** [comment]
I'm closing the issue. Please, reopen it if you have any news on this to share.
